name: Run TypeScript Tests

on:
  pull_request:
    branches:
      - master

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build docker image from root Dockerfile
        run: docker build -t my-test-image:latest -f Dockerfile .

      - name: Run tests in container
        run: docker run --rm my-test-image:latest npm test

      - name: Comment PR if tests fail
        if: failure()
        run: |
          comment="Your tests have failed, see below the failures output:\n"
          curl \
            -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "$comment_url" \
            -d "{\"body\": \"$escaped_comment\"}"
