name: Run TypeScript Tests

on:
  pull_request:
    branches:
      - master

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: built-image:latest
      build:
        dockerfile: Dockerfile
        context: .
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests
        run: npm test

      - name: Comment PR if tests fail
        if: failure()
        run: |
          comment=$'Your tests have failed, see below the failures output:\n'
          curl \
            -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            $comment_url \
            -d "{\"body\": $escaped_comment}"
